### ISSUE TITLE
Ajuda com QRCode

### ISSUE THREAD

**Issue by me269** [odudex/krux_binaries#1]
Boa noite vi seu video no bitconheiros e achei muito legal. Depois de descobrir o projeto da SeedSigner estava procurando um jeito de usar uma coisa parecida com outro hardware já que os Rasberys ficaram muito caros. e achei o Krux bem legal, só que novamente o hardware oficial não se acha mais. Resolvi testar com o Maix-bit já era barato e já tenho a impressora 3d para fazer o case.

Não sei se fiz algo errado(não entendo muito nem de linux nem de programação) mas não consigo fazer o Maix-bit ler nenhum codigo QR. O programa em si acho que esta funcionando ok, consigo navegar pelos menus, gerar carteiras pelas outras opções mas na hora de importar uma seed ou ler um endereço, nada acontece. 

É so fazer o flash do kboot.kfpkg ou precisa fazer alguma coisa antes ou depois para o Maix-Bit ler o QR?

Obrigado pela atenção.

**Comment by odudex** [comment]
Boa noite! Tu és o primeiro aventureiro que sei que está usando o maix Bit. Eu até estava deixando ele meio de lado, mas como agora sei que tem um guerreiro, vou fazer mais testes com ele.
O Bit tem uma coisa um pouco chata que é o ajuste de foco da lente. Tens que girar a lente pra ajustar esse foco até perceber que o QR na tela está como o que estás tentando escanear. Tem que ir na tentativa e erro. Tem que cuidar pra lente estar limpa também.
Agora se estiver dando algum erro, me fale mais detalhes do erro, que tentarei reproduzir aqui.

**Comment by me269** [comment]
Boa noite amigo bitconhero! Realmente o foco é importante mas acho que achei o problema, a imagem esta invertida na tela. Eu espelhei na vertical um qr na tela do computador e reconheceu na hora. Tem algum jeito de gerar um log para poder te mandar?

**Comment by me269** [comment]
Update: Testei inverter na horizontal e também funcionou. Acho seria o mair correto pois durante a leitura a imagem aparece espelhada e não de cabeça para baixo.

**Comment by odudex** [comment]
@me269 interessante, suspeito então que os Bit possam ser enviados com modelos de câmeras diferentes (o que seria uma dor de cabeça enorme).
Tu usas Linux? Se puder conecte teu bit na USB, e use um terminal serial para ler as mensagens que o Bit manda ao ligar, ex. Linux:
```
sudo screen /dev/ttyUSB0 115200

K210 bootloader by LoBo v.1.4.1
* Find applications in MAIN parameters 0: '       firmware', @ 0x00080000, size=1744896,
* app_size=1672064, App ok, ACTIVE* Loading app from flash at 0x00080000 (1672064 B)
* Starting at 0x80000000 ...

[MAIXPY] Pll0:freq:806000000
[MAIXPY] Pll1:freq:398666666
[MAIXPY] Pll2:freq:45066666
[MAIXPY] cpu:freq:403000000
[MAIXPY] kpu:freq:398666666
[MAIXPY] Flash:0xc8:0x17
[MaixPy] gc heap=0x801c5230-0x80295230(851968)
[maixpy] mount sdcard failed
init i2c:2 freq:100000
[MAIXPY]: find ov2640
[MAIXPY]: find ov sensor
```

No Windows podes usar o putty

O meu Bit usa a camera ov2640

Recomendo que entre no grupo no Telegram: https://t.me/KruxBR
Já tem uma turma legal lá, aí podemos compartilhar estes testes com mais "Kruxers".

**Comment by me269** [comment]
O meu usa a camera ov5642. Vou entrar no instagram.

K210 bootloader by LoBo v.1.4.1

                                   * Find applications in MAIN parameters
                                                                             0: '       firmware', @ 0x00080000, size=1744896, app_size=1672064, App ok, ACTIVE
                                                                               * Loading app from flash at 0x00080000 (1672064 B)
                                                 * Starting at 0x80000000 ...


[MAIXPY] Pll0:freq:806000000
[MAIXPY] Pll1:freq:398666666
[MAIXPY] Pll2:freq:45066666
[MAIXPY] cpu:freq:403000000
[MAIXPY] kpu:freq:398666666
[MAIXPY] Flash:0xef:0x17
[MaixPy] gc heap=0x801c5230-0x80295230(851968)
init i2c:2 freq:100000
[MAIXPY]: find ov5642
[MAIXPY]: find ov sensor

**Comment by odudex** [comment]
No Telegram, não Instagram!
Vou gerar um firmware especial pra ti então

**Comment by odudex** [comment]
Experimenta baixar novamente o firmware e rodar:

`./ktool-linux -B goE -b 1500000 maixpy_bit_ov5642/kboot.kfpkg`

**Comment by me269** [comment]
Agora funcionou a captura, só que a imagem da camera fica de cabeça para baixo. Tanto inverter na horizontal quanto na vertical funciona a leitura mas o ideal acho seria inverter na horizontal (mirror), assim mantem a orientação com os menus. Achei a datasheet da camera e la tem os registros usados para inverter a imagem, não sei se ajuda ou é mais facil inverter por software. Vou entrar no instagram. Muito obrigado e parabens pela iniciativa. Quanto mais hardwares compativeis melhor para a comunidade. A seedsigner tb anunciou que já esta providenciando o port para outros hardwares tb por causa do preço do Pi.

**Comment by odudex** [comment]
Ok, fiz mais uma mudança na orientação, se quiser dá uma testada lá

**Comment by me269** [comment]
Ainda ficou de cabeça para baixo. Se inverter novamente na vertical acho que soluciona. Mandei uma foto da ultima alteração.

![P_20220720_122224](https://user-images.githubusercontent.com/109400022/180023391-fb836e38-2594-422a-9d2e-3c3416bdbfcd.jpg)

**Comment by odudex** [comment]
Tem mais uma versão pra testar la, a foto ajudou bastante

**Comment by me269** [comment]
Perfeito!! E a imagem melhorou 1000% depois que vc mudou a camera para a ov5642. Vou continuar testando e começar a projetar um case um pouco diferente do seu para ficar mais compacta usando botoẽs menores. Outros erros que aparecerem posto aqui ou no instagram?

E muito obrigado pelas correções e novamente parabéns pela iniciativa.

**Comment by odudex** [comment]
>Perfeito!! E a imagem melhorou 1000% depois que vc mudou a camera para a ov5642. 

Legal!
Legal que vai fazer um outro case. Compartilha ele depois no grupo ou aqui, vou querer ver!
Se for fazer mais dispositivos, dê uma olhada no [Maix Dock](https://github.com/odudex/DockEncoderCase) também, é o mesmo preço e tem a camera pequena e melhor.

Pode postar os erros e bugs onde preferir.

> E muito obrigado pelas correções e novamente parabéns pela iniciativa.

De nada! Vou encerrar o "issue" aqui
